name: linux

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-22.04, cc: gcc-11 }
          - { os: ubuntu-24.04, cc: gcc-12 }
          - { os: ubuntu-24.04, cc: gcc-13 }
          - { os: ubuntu-22.04, cc: clang }
          - { os: ubuntu-24.04, cc: clang }
    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        sudo apt -q update
        sudo apt install -q -y libfuse-dev ruby-dev libmbedtls-dev
    - name: compiler
      env:
        CC: ${{ matrix.cc }}
      run: sudo apt install -q -y "${CC}"
    - name: build
      env:
        CC: ${{ matrix.cc }}
      run: |
           cmake . -DCMAKE_C_COMPILER="${CC}"
           make VERBOSE=1